### ISSUE TITLE
Performance issue in BLS.aggregate method for v 0.3.3-1

### ISSUE THREAD

**Issue by vikulin** [ConsenSys/jblst#12]
See details in:
https://github.com/supranational/blst/issues/66

**Comment by benjaminion** [comment]
Thanks for the report!

This probably relates more directly to Teku's BLS interface than `jblst` itself.

It looks like the `aggregate` method from the Blst library is [checking group membership](https://github.com/supranational/blst/blob/48f69febca82082298f18e31509670b20f64f2ed/bindings/blst.hpp#L163) for every signature that is aggregated. This slows down aggregation considerably.

I get a ~30x speedup in my naive benchmark if I modify Teku's [signature aggregation](https://github.com/ConsenSys/teku/blob/9c0086ca5af0f90eddc26ca437475adfa7afc914/bls/src/main/java/tech/pegasys/teku/bls/impl/blst/BlstSignature.java#L81) as follows:

```
     P2 sum = new P2();
     for (BlstSignature finiteSignature : signatures) {
-      sum.aggregate(finiteSignature.ec2Point);
+      sum.add(finiteSignature.ec2Point);
     }
```

The group membership check needs to be done somewhere. Previously (Mikuli implementation) we did the membership check at signature deserialisation and not at aggregation. With Blst it looks like the check is not done at deserialisation, but at aggregation time instead.

For Teku, either way is safe, since all our signatures are received over the wire serialised, but I need to think about which place is _best_ to check this.
